[package]
name = "ghstats"
version = "0.1.0"
edition = "2021"

[lints.rust]
dead_code = "allow"

[dependencies]
axum = "0.7.5"
maud = { version = "0.26.0", features = ["axum"] }
reqwest = {version = "0.12.5", features = ["json"] }
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["serde_derive"] }
tokio = { version = "1.38.1", features = ["full"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio", "sqlite"] }
chrono = { version = "0.4.38", features = ["serde"] }
anyhow = "1.0.86"
thousands = "0.2.0"
tokio-cron-scheduler = "0.10.2"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
tower-http = { version = "0.5.2", features = ["trace"] }
dotenvy = "0.15.7"
serde_variant = "0.1.3"
